### ISSUE TITLE
Cannot read properties of undefined (reading 'taskID')

### ISSUE THREAD

**Issue by tuanteku9x** [dkzhen/piggy-bot#1]
I got error, i get query_id is correct

PS D:\Telebot\piggy-bot-main> node index.js
Server is running on port 1001
[ BOT ] : Info mission
TypeError: Cannot read properties of undefined (reading 'taskID')
    at exports.validateToken (D:\Telebot\piggy-bot-main\func\CheckValidToken.js:28:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.CreateStarPay (D:\Telebot\piggy-bot-main\func\CreateStarPay.js:6:20)
[ Error ] : validate token failed
[ BOT ] : Info mission
TypeError: Cannot read properties of undefined (reading 'taskID')
    at exports.validateToken (D:\Telebot\piggy-bot-main\func\CheckValidToken.js:28:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.Task (D:\Telebot\piggy-bot-main\func\Task.js:6:20)
[ Error ] : validate token failed
[ BOT ] : Checking token done..
[ BOT ] : Checking token done..
[ BOT ] : Checking token done..
[ BOT ] : Checking token done..
[ Running ] : Create StarPay successfully. retCode: 10540
Cannot read properties of undefined (reading '1001')

**Comment by dkzhen** [comment]
Oke l will fix next update, thanks u give me issue

**Comment by dkzhen** [comment]
> I got error, i get query_id is correct
> 
> PS D:\Telebot\piggy-bot-main> node index.js Server is running on port 1001 [ BOT ] : Info mission TypeError: Cannot read properties of undefined (reading 'taskID') at exports.validateToken (D:\Telebot\piggy-bot-main\func\CheckValidToken.js:28:51) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async exports.CreateStarPay (D:\Telebot\piggy-bot-main\func\CreateStarPay.js:6:20) [ Error ] : validate token failed [ BOT ] : Info mission TypeError: Cannot read properties of undefined (reading 'taskID') at exports.validateToken (D:\Telebot\piggy-bot-main\func\CheckValidToken.js:28:51) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async exports.Task (D:\Telebot\piggy-bot-main\func\Task.js:6:20) [ Error ] : validate token failed [ BOT ] : Checking token done.. [ BOT ] : Checking token done.. [ BOT ] : Checking token done.. [ BOT ] : Checking token done.. [ Running ] : Create StarPay successfully. retCode: 10540 Cannot read properties of undefined (reading '1001')

bug has been fixed, you can try again
